Login: Login
LoginVerb: Login
Username: Username
Password: Password
ProjectName: Keskisen Tila
LoginTitle: Keskisen Tila Login
GeneralTitle: Keskisen Tila Forms
ChangePassword: Change Password
OldPassword: Old password
NewPassword: New password
Submit: Submit
WrongOld: Old password wrong
PasswordUpdated: Password updated
Admin: Admin
Manager: Manager
Worker: Worker
AddUser: Add User
Error: Error happened submitting the form
UserAdded: User added successfully
Name: Name
UserType: Type
Forms: Forms
ChangeUserPassword: Change user password
NoSuchUser: No such user was found
Count: Count
Info: Info
TestForm1: Test form 1
TestForm2: Test form 2
TestForm3: Test form 3
FormSuccess: Form sent succesfully
TestWithWorker: Test with worker
Rating: Rating
Date: Date
Time: Time
TestWithDateControls: Test with date controls
