Login: Kirjautuminen
LoginVerb: Kirjaudu
Username: Käyttäjänimi
Password: Salasana
ProjectName: Keskisen Tila
LoginTitle: Keskisen Tila Kirjautuminen
GeneralTitle: Keskisen Tila Lomakkeet
ChangePassword: Vaihda salasana
OldPassword: Vanha salasana
NewPassword: Uusi salasana
Submit: Lähetä
WrongOld: Vanha salasana väärin
PasswordUpdated: Salasana päivitetty
Admin: Admin
Manager: Manageri
Worker: Työntekijä
AddUser: Lisää käyttäjä
Error: Virhe lomaketta lähetettäessä
UserAdded: Käyttäjä lisätty onnistuneesti
Name: Nimi
UserType: Tyyppi
Forms: Lomakkeet
ChangeUserPassword: Vaihda käyttäjän salasana
NoSuchUser: Ei käyttäjää annetulla nimellä
Count: Määrä
Info: Info
TestForm1: Testi lomake 1
TestForm2: Testi lomake 2
TestForm3: Testi lomake 3
FormSuccess: Lomake lähetetty onnistuneesti
TestWithWorker: Testi lomake työntekijällä
Rating: Arvosana
Date: Päivä
Time: Aika
TestWithDateControls: Testi päivä kontrolleilla
